//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuisnessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class GamePlayed
    {
        public int ID { get; set; }
        public Nullable<int> HomeTeamID { get; set; }
        public Nullable<int> HomeGoalieID { get; set; }
        public Nullable<int> HomeScore { get; set; }
        public Nullable<int> AwayTeamID { get; set; }
        public Nullable<int> AwayGoalieID { get; set; }
        public Nullable<int> AwayScore { get; set; }
    
        public virtual Goalies Goalies { get; set; }
        public virtual Teams Teams { get; set; }
        public virtual Goalies Goalies1 { get; set; }
        public virtual Teams Teams1 { get; set; }
    }
}
